version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo Installing dependencies...
      - apt-get update -y
      - apt-get install -y unzip
  pre_build:
    commands:
      - echo Pre-build stage started...
      - mkdir -p /tmp/deploy
  build:
    commands:
      - echo Build started...
      - cp -r car/* /tmp/deploy/
      - echo PHP lint check...
      - find car -name "*.php" -exec php -l {} \;
  post_build:
    commands:
      - echo Build completed.
      - echo Ready to deploy.

artifacts:
  files:
    - '**/*'
  base-directory: /tmp/deploy
