branch-defaults:
  default:
    environment: DevOps-webapp-env1
global:
  application_name: DevOps-webapp
  default_region: ap-southeast-2
  profile: null
  solution_stack: 64bit Amazon Linux 2 v4.6.2 running PHP 8.4
  workspace_type: Application
