version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - sudo apt-get update -y
      - sudo apt-get install -y php php-cli apache2 # Installing PHP and Apache2 for running PHP

  build:
    commands:
      - echo "Build block"
      - ls -R car # List the contents of the 'car' directory to ensure all files are in place
      - echo "Checking for 'header.php' inclusion in index.php"
      - grep "header.php" car/index.php # Ensure that header.php is included correctly
      - echo "Checking PHP syntax in index.php"
      - php -l car/index.php # Run PHP syntax check on index.php file to ensure no errors

  post_build:
    commands:
      - echo "Post build phase"
      - echo "Build and tests completed."
      - echo "Starting Apache server to serve the PHP files."
      - sudo service apache2 start # Starting Apache to serve the PHP website
